import edu.pradita.p14.javafx.ShippingMerek;
import edu.pradita.p14.javafx.dao.ShippingMerekDao;
import edu.pradita.p14.javafx.dao.ShippingMerekDaoImpl;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class ShippingMerekDaoImplTest {

    private static ShippingMerekDao shippingMerekDao;

    @BeforeAll
    static void setUp() {
        shippingMerekDao = new ShippingMerekDaoImpl();
    }

    // PERBAIKAN: Tambahkan "throws Exception" di sini
    @Test
    void testSaveAndFindById() throws Exception {
        // 1. Create a new object
        ShippingMerek newMerek = new ShippingMerek("Test Brand", 99.99, "Test Type");

        // 2. Save it using the DAO
        // Pemanggilan ini sekarang aman karena method test sudah siap menangani Exception
        shippingMerekDao.save(newMerek);

        // The ID is generated by the database, so it should not be 0
        assertNotEquals(0, newMerek.getId());

        // 3. Retrieve it using the ID
        // Pemanggilan ini juga sudah aman
        ShippingMerek foundMerek = shippingMerekDao.findById(newMerek.getId());

        // 4. Assert that the retrieved object is the same
        assertNotNull(foundMerek);
        assertEquals("Test Brand", foundMerek.getName());
    }
}